import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { LevelProvider } from "./context/LevelContext";
import { PlayerProvider } from "./context/PlayerContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LevelProvider>
          <PlayerProvider>
            <main>{children}</main>
            <Script src="https://cdn.pannellum.org/2.5/pannellum.js"></Script>
          </PlayerProvider>
        </LevelProvider>
      </body>
    </html>
  );
}
